In [62]:
import pandas as pd
import numpy as np
from scipy.stats import mode

In [66]:
iris = pd.read_csv('Data_Iris.csv', header=None)
iris.columns = ['x1', 'x2', 'x3', 'x4', 'class']
iris.index = range(1, len(iris) + 1)

In [13]:
iris

      x1   x2   x3   x4           class
1    5.1  3.5  1.4  0.2     Iris-setosa
2    4.9  3.0  1.4  0.2     Iris-setosa
3    4.7  3.2  1.3  0.2     Iris-setosa
4    4.6  3.1  1.5  0.2     Iris-setosa
5    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
146  6.7  3.0  5.2  2.3  Iris-virginica
147  6.3  2.5  5.0  1.9  Iris-virginica
148  6.5  3.0  5.2  2.0  Iris-virginica
149  6.2  3.4  5.4  2.3  Iris-virginica
150  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [51]:
# Kelompokkan data berdasarkan kelasnya
grouped_data = iris.groupby('class')

# Inisialisasi list untuk menyimpan data pelatihan dan data testing
train_data = []
test_data = []

# Ambil 10 data terakhir dari setiap kelas sebagai data testing
for _, group in grouped_data:
    test_data.append(group.tail(10))
    train_data.append(group.iloc[:-10])

# Gabungkan data pelatihan dan data testing
train_data = pd.concat(train_data)
test_data = pd.concat(test_data)

class_mapping = {'Iris-setosa': 1, 'Iris-versicolor': 2, 'Iris-virginica': 3}

train_data['label'] = train_data['class'].map(class_mapping)
test_data['label'] = test_data['class'].map(class_mapping)

train_data.drop(columns=['class'], inplace=True)
test_data.drop(columns=['class'], inplace=True)

In [29]:
print("\nData Testing:")
test_data

Data Testing:

      x1   x2   x3   x4  label
41   5.0  3.5  1.3  0.3      1
42   4.5  2.3  1.3  0.3      1
43   4.4  3.2  1.3  0.2      1
44   5.0  3.5  1.6  0.6      1
45   5.1  3.8  1.9  0.4      1
46   4.8  3.0  1.4  0.3      1
47   5.1  3.8  1.6  0.2      1
48   4.6  3.2  1.4  0.2      1
49   5.3  3.7  1.5  0.2      1
50   5.0  3.3  1.4  0.2      1
91   5.5  2.6  4.4  1.2      2
92   6.1  3.0  4.6  1.4      2
93   5.8  2.6  4.0  1.2      2
94   5.0  2.3  3.3  1.0      2
95   5.6  2.7  4.2  1.3      2
96   5.7  3.0  4.2  1.2      2
97   5.7  2.9  4.2  1.3      2
98   6.2  2.9  4.3  1.3      2
99   5.1  2.5  3.0  1.1      2
100  5.7  2.8  4.1  1.3      2
141  6.7  3.1  5.6  2.4      3
142  6.9  3.1  5.1  2.3      3
143  5.8  2.7  5.1  1.9      3
144  6.8  3.2  5.9  2.3      3
145  6.7  3.3  5.7  2.5      3
146  6.7  3.0  5.2  2.3      3
147  6.3  2.5  5.0  1.9      3
148  6.5  3.0  5.2  2.0      3
149  6.2  3.4  5.4  2.3      3
150  5.9  3.0  5.1  1.8      3

In [30]:
print("Data Training:")
train_data

Data Training:

      x1   x2   x3   x4  label
1    5.1  3.5  1.4  0.2      1
2    4.9  3.0  1.4  0.2      1
3    4.7  3.2  1.3  0.2      1
4    4.6  3.1  1.5  0.2      1
5    5.0  3.6  1.4  0.2      1
..   ...  ...  ...  ...    ...
136  7.7  3.0  6.1  2.3      3
137  6.3  3.4  5.6  2.4      3
138  6.4  3.1  5.5  1.8      3
139  6.0  3.0  4.8  1.8      3
140  6.9  3.1  5.4  2.1      3

[120 rows x 5 columns]

In [47]:
# Fungsi untuk menghitung jarak Euclidean antara dua vektor
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Inisialisasi list untuk menyimpan hasil perhitungan jarak Euclidean
distances = []

# Loop untuk setiap data testing dan data pelatihan
for _, test_row in test_data.iterrows():
    row_distances = []
    for _, train_row in train_data.iterrows():
        test_features = test_row[['x1', 'x2', 'x3', 'x4']].values
        train_features = train_row[['x1', 'x2', 'x3', 'x4']].values
        
        # Hitung jarak Euclidean antara data testing dan data pelatihan
        distance = euclidean_distance(test_features, train_features)
        row_distances.append(distance)
    distances.append(row_distances)
    
    # Urutkan jarak dari terkecil ke terbesar dan ambil 5 jarak terpendek
    nearest_distances.append(sorted(distances)[:5])

distances = np.array(distances)

# Cetak hasil perhitungan jarak Euclidean
print("Euclidean Distance:")
print(distances)

Euclidean Distance:
[[0.17320508 0.52915026 0.43588989 ... 4.69148164 3.96862697 4.88057374]
 [1.34907376 0.81853528 0.92736185 ... 4.9132474  4.1521079  5.14295635]
 [0.76811457 0.54772256 0.3        ... 4.92036584 4.17252921 5.16526863]
 ...
 [4.45982062 4.49888875 4.66154481 ... 0.38729833 0.67082039 0.46904158]
 [4.65080638 4.71805044 4.84871117 ... 0.6244998  0.9        0.78740079]
 [4.14004831 4.15331193 4.29883705 ... 0.64807407 0.31622777 1.09087121]]

In [58]:
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

nearest_distances = []

# Loop untuk setiap data testing
for _, test_row in test_data.iterrows():
    distances = []  # List untuk menyimpan jarak terhadap setiap data pelatihan
    for _, train_row in train_data.iterrows():
        test_features = test_row[['x1', 'x2', 'x3', 'x4']].values
        train_features = train_row[['x1', 'x2', 'x3', 'x4']].values
        
        # Hitung jarak Euclidean antara data testing dan data pelatihan
        distance = euclidean_distance(test_features, train_features)
        
        # Tambahkan jarak ke dalam list distances
        distances.append(distance)
    
    # Urutkan jarak dari terkecil ke terbesar dan ambil 5 jarak terpendek
    nearest_distances.append(sorted(distances)[:5])


print("KNN:")
for i, distances in enumerate(nearest_distances, 1):
    print(f"D{i}: {distances}")

KNN:
D1: [0.14142135623730917, 0.17320508075688743, 0.17320508075688767, 0.2449489742783178, 0.2645751311064589]
D2: [0.6244997998398398, 0.7141428428542852, 0.7810249675906656, 0.7937253933193773, 0.8185352771872454]
D3: [0.20000000000000018, 0.29999999999999954, 0.2999999999999998, 0.3162277660168373, 0.31622776601683816]
D4: [0.22360679774997896, 0.264575131106459, 0.31622776601683794, 0.37416573867739417, 0.42426406871192857]
D5: [0.3741657386773947, 0.41231056256176585, 0.41231056256176596, 0.5099019513592782, 0.5385164807134503]
D6: [0.14142135623730986, 0.19999999999999998, 0.24494897427831797, 0.264575131106459, 0.26457513110645925]
D7: [0.14142135623730953, 0.24494897427831772, 0.2999999999999998, 0.33166247903554, 0.3316624790355405]
D8: [0.14142135623730964, 0.14142135623730978, 0.22360679774997871, 0.22360679774997935, 0.2999999999999996]
D9: [0.10000000000000053, 0.22360679774997896, 0.2449489742783178, 0.2828427124746191, 0.30000000000000027]
D10: [0.14142135623730964, 0.17320508075688762, 0.22360679774997877, 0.22360679774997896, 0.22360679774997916]
D11: [0.3162277660168378, 0.42426406871192884, 0.4795831523312723, 0.509901951359279, 0.519615242270663]
D12: [0.14142135623730995, 0.19999999999999973, 0.30000000000000027, 0.38729833462074226, 0.4242640687119287]
D13: [0.14142135623730964, 0.24494897427831766, 0.2645751311064592, 0.3316624790355399, 0.37416573867739383]
D14: [0.1414213562373093, 0.3605551275463989, 0.6480740698407862, 0.7211102550927979, 0.7874007874011814]
D15: [0.30000000000000016, 0.31622776601683794, 0.33166247903553986, 0.3741657386773944, 0.37416573867739444]
D16: [0.1732050807568884, 0.36055512754639907, 0.3741657386773941, 0.3872983346207416, 0.43588989435406733]
D17: [0.1732050807568884, 0.3000000000000001, 0.31622776601683783, 0.38729833462074165, 0.3872983346207417]
D18: [0.20000000000000018, 0.33166247903554, 0.3464101615137756, 0.3872983346207415, 0.42426406871192895]
D19: [0.3872983346207412, 0.7211102550927979, 0.7937253933193776, 0.8185352771872454, 0.9]
D20: [0.22360679774997935, 0.26457513110645864, 0.3316624790355398, 0.36055512754639923, 0.374165738677394]
D21: [0.26457513110645947, 0.34641016151377513, 0.360555127546399, 0.374165738677394, 0.4123105625617657]
D22: [0.3605551275463994, 0.4690415759823433, 0.5099019513592786, 0.5477225575051662, 0.6082762530298225]
D23: [0.0, 0.26457513110645897, 0.31622776601683755, 0.3605551275463989, 0.47958315233127147]
D24: [0.22360679774997935, 0.31622776601683766, 0.3872983346207417, 0.4123105625617659, 0.4898979485566359]
D25: [0.30000000000000016, 0.3999999999999999, 0.43588989435406783, 0.47958315233127174, 0.5000000000000001]
D26: [0.360555127546399, 0.3741657386773938, 0.374165738677394, 0.4242640687119287, 0.5477225575051657]
D27: [0.24494897427831777, 0.3741657386773942, 0.38729833462074154, 0.41231056256176585, 0.47958315233127174]
D28: [0.22360679774997935, 0.34641016151377513, 0.3605551275463988, 0.3872983346207415, 0.3872983346207415]
D29: [0.2449489742783171, 0.3000000000000001, 0.5567764362830023, 0.6244997998398396, 0.6244997998398396]
D30: [0.282842712474618, 0.31622776601683766, 0.33166247903553997, 0.3605551275463989, 0.37416573867739383]